"""링크② RTDS(서버)–EMS(클라) — 프로토콜맵 시트2.

EMS → RTDS 쓰기: ESS 디지털 지령 Coil·지령/제한 HR
RTDS → EMS 읽기: PCS/ESS 상태 DI·계측/상세 IR
매니저는 이 링크의 당사자가 아니다 (에뮬레이터·평가 참조용 정의).
"""
from .types import DType, Link, LinkMap, ObjType, RegisterDef

_L = Link.LINK2
_regs: list[RegisterDef] = [
    # ── Coils (FC05/15) — EMS → RTDS 쓰기 (ESS 디지털 지령) ──
    RegisterDef(_L, ObjType.COIL, 0, "ess_run_enable", "ESS 운전 Enable", DType.BIT, note="ESS ON/OFF"),
    RegisterDef(_L, ObjType.COIL, 1, "control_enable", "제어 Enable", DType.BIT, note="제어 지령 활성"),
    RegisterDef(_L, ObjType.COIL, 2, "e_stop", "비상정지(E-Stop)", DType.BIT, note="안전 정지"),
    RegisterDef(_L, ObjType.COIL, 3, "discharge_enable", "PCS 방전 Enable", DType.BIT),
    RegisterDef(_L, ObjType.COIL, 4, "charge_enable", "PCS 충전 Enable", DType.BIT),
    RegisterDef(_L, ObjType.COIL, 5, "fault_reset", "고장 리셋(Fault Reset)", DType.BIT, note="PCS 고장 해제"),
    # ── Holding Registers (FC06/16) — EMS → RTDS 쓰기 (ESS/PCS 지령·제한) ──
    RegisterDef(_L, ObjType.HR, 0, "ess_control_mode", "ESS 제어 모드", DType.UINT16, 1, "",
                "0자동/1수동/2경제/3피크저감 — Run A=2, Run B=3"),
    RegisterDef(_L, ObjType.HR, 1, "p_command", "유효전력 P 지령", DType.INT16, 100, "kW",
                "±250.00, +방전/−충전"),
    RegisterDef(_L, ObjType.HR, 2, "q_command", "무효전력 Q 지령", DType.INT16, 100, "kvar",
                "±250.00, +진상/−지상"),
    RegisterDef(_L, ObjType.HR, 3, "pf_command", "역률 지령", DType.INT16, 1000, "",
                "−1.000~1.000"),
    RegisterDef(_L, ObjType.HR, 4, "reactive_mode", "무효전력 제어 모드", DType.UINT16, 1, "",
                "0:Q고정/1:PF고정/2:Q(V)"),
    RegisterDef(_L, ObjType.HR, 5, "target_soc", "ESS 목표 SOC", DType.UINT16, 100, "%", "0~100"),
    RegisterDef(_L, ObjType.HR, 6, "soc_max", "SOC 운전 상한", DType.UINT16, 100, "%", "0~100"),
    RegisterDef(_L, ObjType.HR, 7, "soc_min", "SOC 운전 하한", DType.UINT16, 100, "%", "0~100"),
    RegisterDef(_L, ObjType.HR, 8, "discharge_limit", "방전량 제한", DType.UINT16, 100, "kW",
                "0~655.35, HMI_Plim_pos"),
    RegisterDef(_L, ObjType.HR, 9, "charge_limit", "충전량 제한", DType.UINT16, 100, "kW",
                "0~655.35, HMI_Plim_neg"),
    RegisterDef(_L, ObjType.HR, 10, "controller_watchdog", "컨트롤러 워치독", DType.UINT16, 1, "",
                "EMS 주기 +1, 3주기 정체 시 PCS 안전상태"),
    RegisterDef(_L, ObjType.HR, 11, "cmd_seq", "CMD Sequence No.", DType.UINT16, 1, "",
                "신규 지령 +1 — 블록 기록 완료 후 마지막에 증가(원자성)"),
    # ── Discrete Inputs (FC02) — RTDS → EMS 읽기 (PCS/ESS 상태) ──
    RegisterDef(_L, ObjType.DI, 0, "rtds_running", "RTDS 운전중", DType.BIT),
    RegisterDef(_L, ObjType.DI, 1, "ess_charging", "ESS 충전중", DType.BIT),
    RegisterDef(_L, ObjType.DI, 2, "ess_discharging", "ESS 방전중", DType.BIT),
    RegisterDef(_L, ObjType.DI, 3, "ess_ready", "ESS 가용(Ready)", DType.BIT),
    RegisterDef(_L, ObjType.DI, 4, "grid_tied", "계통 연계(Grid-tied)", DType.BIT, note="연계=1/해렬=0"),
    RegisterDef(_L, ObjType.DI, 5, "rtds_pcs_fault", "RTDS/PCS 고장", DType.BIT,
                note="상세는 고장 워드 IR 300029"),
    # ── Input Registers (FC04) — RTDS → EMS 읽기 (계측·PCS 상세) ──
    RegisterDef(_L, ObjType.IR, 0, "res_seq", "RES Sequence No.", DType.UINT16, 1, "",
                "신규 결과 +1 — 변화 시에만 스냅샷 래치"),
    RegisterDef(_L, ObjType.IR, 1, "result_interval", "결과 해당 구간", DType.UINT16, 1, "", "0~95"),
    RegisterDef(_L, ObjType.IR, 2, "pv_power", "PV 발전량", DType.UINT16, 100, "kW", "0~655.35"),
    RegisterDef(_L, ObjType.IR, 3, "load_power", "부하량(실측)", DType.UINT16, 100, "kW",
                "0~655.35 — 부하 예측률 평가 ground truth"),
    RegisterDef(_L, ObjType.IR, 4, "ess_power", "ESS 충방전 전력(실제)", DType.INT16, 100, "kW",
                "±327.67, +방전/−충전"),
    RegisterDef(_L, ObjType.IR, 5, "ess_soc", "ESS SOC(요약)", DType.UINT16, 100, "%", "0~100"),
    RegisterDef(_L, ObjType.IR, 6, "pcc_import", "PCC 수전전력(import)", DType.UINT16, 100, "kW",
                "0~655.35, 요금 산정"),
    RegisterDef(_L, ObjType.IR, 7, "pcc_export", "PCC 역송전력(export)", DType.UINT16, 100, "kW",
                "0~655.35"),
    RegisterDef(_L, ObjType.IR, 8, "pcc_voltage", "PCC 전압", DType.UINT16, 100, "V", "0~655.35"),
    RegisterDef(_L, ObjType.IR, 9, "grid_freq", "계통 주파수", DType.UINT16, 100, "Hz", "예 60.00"),
    RegisterDef(_L, ObjType.IR, 10, "v_ab", "계통 A-B 선간전압", DType.UINT16, 100, "V", "HMI_Va"),
    RegisterDef(_L, ObjType.IR, 11, "v_bc", "계통 B-C 선간전압", DType.UINT16, 100, "V", "HMI_Vb"),
    RegisterDef(_L, ObjType.IR, 12, "v_ca", "계통 C-A 선간전압", DType.UINT16, 100, "V", "HMI_Vc"),
    RegisterDef(_L, ObjType.IR, 13, "i_a", "A상 전류", DType.UINT16, 100, "A", "HMI_Ia"),
    RegisterDef(_L, ObjType.IR, 14, "i_b", "B상 전류", DType.UINT16, 100, "A", "HMI_Ib"),
    RegisterDef(_L, ObjType.IR, 15, "i_c", "C상 전류", DType.UINT16, 100, "A", "HMI_Ic"),
    RegisterDef(_L, ObjType.IR, 16, "pcs_p", "PCS 유효전력(계측)", DType.INT16, 100, "kW",
                "±327.67, HMI_Pac"),
    RegisterDef(_L, ObjType.IR, 17, "pcs_q", "PCS 무효전력 Q(계측)", DType.INT16, 100, "kvar",
                "±327.67, +진상/−지상"),
    RegisterDef(_L, ObjType.IR, 18, "pcs_s", "PCS 피상전력 S(계측)", DType.UINT16, 100, "kVA",
                "0~655.35"),
    RegisterDef(_L, ObjType.IR, 19, "pcs_pf", "역률 PF(계측)", DType.INT16, 1000, "",
                "−1.000~1.000"),
    RegisterDef(_L, ObjType.IR, 20, "dc_link_voltage", "DC 링크 전압", DType.UINT16, 50, "V",
                "0~1310.70, HMI_Vdc"),
    RegisterDef(_L, ObjType.IR, 21, "bank_soc", "ESS Bank SOC", DType.UINT16, 10, "%",
                "0~1000, 0.1% 분해능"),
    RegisterDef(_L, ObjType.IR, 22, "bank_soh", "ESS Bank SOH", DType.UINT16, 10, "%",
                "0~1000, 0.1% 분해능"),
    RegisterDef(_L, ObjType.IR, 23, "bank_voltage", "ESS Bank 전압", DType.UINT16, 50, "V",
                "0~1310.70"),
    RegisterDef(_L, ObjType.IR, 24, "bank_current", "ESS Bank 전류", DType.INT16, 50, "A",
                "±655.34, +방전(DC)"),
    RegisterDef(_L, ObjType.IR, 25, "bank_power", "ESS Bank 전력", DType.INT16, 100, "kW",
                "±327.67, −충전"),
    RegisterDef(_L, ObjType.IR, 26, "pcs_temp", "PCS 온도", DType.INT16, 10, "℃",
                "±3276.7, IGBT/내부"),
    RegisterDef(_L, ObjType.IR, 27, "battery_temp", "배터리 온도", DType.INT16, 10, "℃",
                "±3276.7, 최고 셀"),
    RegisterDef(_L, ObjType.IR, 28, "pcs_state_word", "PCS 운전상태 워드", DType.UINT16, 1, "",
                "0정지/1대기/2운전/3계통연계/4고장"),
    RegisterDef(_L, ObjType.IR, 29, "fault_word", "고장·알람 워드", DType.UINT16, 1, "",
                "비트맵: b0과전압/b1과전류/b2과온/b3지락/b4계통/b5통신"),
    RegisterDef(_L, ObjType.IR, 30, "rtds_status_code", "RTDS 상태코드", DType.UINT16, 1, "",
                "0정상/1주의/2고장"),
    RegisterDef(_L, ObjType.IR, 31, "discharge_cmd_echo", "방전 지령 echo", DType.UINT16, 100, "kW",
                "Order_P_pos(적용값)"),
    RegisterDef(_L, ObjType.IR, 32, "charge_cmd_echo", "충전 지령 echo", DType.UINT16, 100, "kW",
                "Order_P_neg(적용값)"),
    RegisterDef(_L, ObjType.IR, 33, "discharge_energy_hi", "누적 방전 전력량(Hi)", DType.UINT16, 1, "",
                "UINT32 상위워드"),
    RegisterDef(_L, ObjType.IR, 34, "discharge_energy_lo", "누적 방전 전력량(Lo)", DType.UINT16, 1, "kWh",
                "UINT32 하위워드, big-endian, 결합값 ×10 kWh"),
    RegisterDef(_L, ObjType.IR, 35, "charge_energy_hi", "누적 충전 전력량(Hi)", DType.UINT16, 1, "",
                "UINT32 상위워드"),
    RegisterDef(_L, ObjType.IR, 36, "charge_energy_lo", "누적 충전 전력량(Lo)", DType.UINT16, 1, "kWh",
                "UINT32 하위워드, big-endian, 결합값 ×10 kWh"),
]

LINK2 = LinkMap(link=_L, server="RTDS", client="EMS", registers=_regs)
